export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const FURNITURE_ROUTE = '/furniture'
